config/routes.rb
# == Route Map
#
#                             Prefix Verb   URI Pattern                                   Controller#Action
#                      user_password POST   /users/password(.:format)                     devise/passwords#create
#                  new_user_password GET    /users/password/new(.:format)                 devise/passwords#new
#                 edit_user_password GET    /users/password/edit(.:format)                devise/passwords#edit
#                                    PATCH  /users/password(.:format)                     devise/passwords#update
#                                    PUT    /users/password(.:format)                     devise/passwords#update
#           cancel_user_registration GET    /users/cancel(.:format)                       devise/registrations#cancel
#                  user_registration POST   /users(.:format)                              devise/registrations#create
#              new_user_registration GET    /users/sign_up(.:format)                      devise/registrations#new
#             edit_user_registration GET    /users/edit(.:format)                         devise/registrations#edit
#                                    PATCH  /users(.:format)                              devise/registrations#update
#                                    PUT    /users(.:format)                              devise/registrations#update
#                                    DELETE /users(.:format)                              devise/registrations#destroy
#                  user_confirmation POST   /users/confirmation(.:format)                 confirmations#create
#              new_user_confirmation GET    /users/confirmation/new(.:format)             confirmations#new
#                                    GET    /users/confirmation(.:format)                 confirmations#show
#                        user_unlock POST   /users/unlock(.:format)                       devise/unlocks#create
#                    new_user_unlock GET    /users/unlock/new(.:format)                   devise/unlocks#new
#                                    GET    /users/unlock(.:format)                       devise/unlocks#show
#                   new_user_session GET    /login(.:format)                              devise/sessions#new
#                       user_session POST   /login(.:format)                              devise/sessions#create
#               destroy_user_session DELETE /logout(.:format)                             devise/sessions#destroy
#                            confirm PATCH  /confirm(.:format)                            confirmations#confirm
#                      new_user_join GET    /join(.:format)                               devise/registrations#new
#                resend_confirmation GET    /re-confirm(.:format)                         devise/confirmations#new
#                    forgot_password GET    /forgot-password(.:format)                    devise/passwords#new
#                     unlock_account GET    /unlock(.:format)                             devise/unlocks#new
#                               root GET    /                                             welcome#index
#                      subscriptions GET    /subscriptions(.:format)                      subscriptions#index
#                                    POST   /subscriptions(.:format)                      subscriptions#create
#                       subscription DELETE /subscriptions/:id(.:format)                  subscriptions#destroy
#                         admin_root GET    /admin(.:format)                              admin/dashboard#index
#                    admin_dashboard GET    /admin/dashboard(.:format)                    admin/dashboard#index
#    batch_action_admin_ex_documents POST   /admin/ex_documents/batch_action(.:format)    admin/ex_documents#batch_action
#                 admin_ex_documents GET    /admin/ex_documents(.:format)                 admin/ex_documents#index
#                                    POST   /admin/ex_documents(.:format)                 admin/ex_documents#create
#              new_admin_ex_document GET    /admin/ex_documents/new(.:format)             admin/ex_documents#new
#             edit_admin_ex_document GET    /admin/ex_documents/:id/edit(.:format)        admin/ex_documents#edit
#                  admin_ex_document GET    /admin/ex_documents/:id(.:format)             admin/ex_documents#show
#                                    PATCH  /admin/ex_documents/:id(.:format)             admin/ex_documents#update
#                                    PUT    /admin/ex_documents/:id(.:format)             admin/ex_documents#update
#                                    DELETE /admin/ex_documents/:id(.:format)             admin/ex_documents#destroy
#         batch_action_admin_ex_tags POST   /admin/ex_tags/batch_action(.:format)         admin/ex_tags#batch_action
#                      admin_ex_tags GET    /admin/ex_tags(.:format)                      admin/ex_tags#index
#                                    POST   /admin/ex_tags(.:format)                      admin/ex_tags#create
#                   new_admin_ex_tag GET    /admin/ex_tags/new(.:format)                  admin/ex_tags#new
#                  edit_admin_ex_tag GET    /admin/ex_tags/:id/edit(.:format)             admin/ex_tags#edit
#                       admin_ex_tag GET    /admin/ex_tags/:id(.:format)                  admin/ex_tags#show
#                                    PATCH  /admin/ex_tags/:id(.:format)                  admin/ex_tags#update
#                                    PUT    /admin/ex_tags/:id(.:format)                  admin/ex_tags#update
#                                    DELETE /admin/ex_tags/:id(.:format)                  admin/ex_tags#destroy
# batch_action_admin_stock_companies POST   /admin/stock_companies/batch_action(.:format) admin/stock_companies#batch_action
#              admin_stock_companies GET    /admin/stock_companies(.:format)              admin/stock_companies#index
#                                    POST   /admin/stock_companies(.:format)              admin/stock_companies#create
#            new_admin_stock_company GET    /admin/stock_companies/new(.:format)          admin/stock_companies#new
#           edit_admin_stock_company GET    /admin/stock_companies/:id/edit(.:format)     admin/stock_companies#edit
#                admin_stock_company GET    /admin/stock_companies/:id(.:format)          admin/stock_companies#show
#                                    PATCH  /admin/stock_companies/:id(.:format)          admin/stock_companies#update
#                                    PUT    /admin/stock_companies/:id(.:format)          admin/stock_companies#update
#                                    DELETE /admin/stock_companies/:id(.:format)          admin/stock_companies#destroy
#   batch_action_admin_subscriptions POST   /admin/subscriptions/batch_action(.:format)   admin/subscriptions#batch_action
#                admin_subscriptions GET    /admin/subscriptions(.:format)                admin/subscriptions#index
#                                    POST   /admin/subscriptions(.:format)                admin/subscriptions#create
#             new_admin_subscription GET    /admin/subscriptions/new(.:format)            admin/subscriptions#new
#            edit_admin_subscription GET    /admin/subscriptions/:id/edit(.:format)       admin/subscriptions#edit
#                 admin_subscription GET    /admin/subscriptions/:id(.:format)            admin/subscriptions#show
#                                    PATCH  /admin/subscriptions/:id(.:format)            admin/subscriptions#update
#                                    PUT    /admin/subscriptions/:id(.:format)            admin/subscriptions#update
#                                    DELETE /admin/subscriptions/:id(.:format)            admin/subscriptions#destroy
#           batch_action_admin_users POST   /admin/users/batch_action(.:format)           admin/users#batch_action
#                        admin_users GET    /admin/users(.:format)                        admin/users#index
#                                    POST   /admin/users(.:format)                        admin/users#create
#                     new_admin_user GET    /admin/users/new(.:format)                    admin/users#new
#                    edit_admin_user GET    /admin/users/:id/edit(.:format)               admin/users#edit
#                         admin_user GET    /admin/users/:id(.:format)                    admin/users#show
#                                    PATCH  /admin/users/:id(.:format)                    admin/users#update
#                                    PUT    /admin/users/:id(.:format)                    admin/users#update
#                                    DELETE /admin/users/:id(.:format)                    admin/users#destroy
#                      resque_server        /resque                                       Resque::Server
#

Rails.application.routes.draw do
  root 'welcome#index'

  resources :subscriptions, only: [:index, :create, :destroy]

  devise_for :users, :skip => [:sessions], :controllers => {:confirmations => 'confirmations'}
  as :user do
    # session controller
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    # confirmable
    patch 'confirm' => "confirmations#confirm"
    # seo links
    get 'join' => 'devise/registrations#new', :as => :new_user_join
    get 're-confirm' => 'devise/confirmations#new', :as => :resend_confirmation
    get 'forgot-password' => 'devise/passwords#new', :as => :forgot_password
    get 'unlock' => 'devise/unlocks#new', :as => :unlock_account
  end

  ActiveAdmin.routes(self)

  if Rails.env.development?
    mount Resque::Server, :at => "/resque"
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
    <!-- Footer Links -->
    <div class="row">
        <div class="col-sm-4">
            <h4 class="footer-heading">Company</h4>
            <ul class="footer-nav ul-breath list-unstyled">
                <li><a href="javascript:void(0)">About Us</a></li>
                <li><a href="javascript:void(0)">Our Team</a></li>
                <li><a href="javascript:void(0)">Pricing</a></li>
                <li><a href="javascript:void(0)">Terms &amp; Conditions</a></li>
                <li><a href="javascript:void(0)">Privacy Policy</a></li>
            </ul>
        </div>
        <div class="col-sm-4">
            <h4 class="footer-heading">Need support?</h4>
            <ul class="footer-nav footer-nav-links list-inline">
                <%= render 'layouts/support_links' %>
            </ul>
            <h4 class="footer-heading">We are social!</h4>
            <ul class="footer-nav footer-nav-links list-inline">
                <%= render 'layouts/social_links' %>
            </ul>
        </div>
        <div class="col-sm-4">
            <h4 class="footer-heading">Newsletter</h4>
            <%= render 'layouts/newsletter_form' %>
            <h4 class="footer-heading"><a href="http://www.hkStockOwl.com">hkStockOwl</a></h4>
            <em><span id="year-copy"></span></em> &copy; Crafted with <i class="fa fa-heart text-danger"></i> in Hong Kong
        </div>
    </div>
    <!-- END Footer Links -->
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container">
  <!-- Site Logo -->
  <%= link_to 'hkStockOwl', root_path, class: 'site-logo' %>
  <!-- END Site Logo -->

  <!-- Site Navigation -->
  <nav>
    <!-- Menu Toggle -->
    <!-- Toggles menu on small screens -->
    <a href="javascript:void(0)" class="btn btn-default site-menu-toggle visible-xs visible-sm">
      Menu
    </a>
    <!-- END Menu Toggle -->

    <!-- Main Menu -->
    <ul class="site-nav">
      <%= render 'layouts/navigation_links' %>
    </ul>
    <!-- END Main Menu -->
  </nav>
  <!-- END Site Navigation -->
</div>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to "Edit account", edit_user_registration_path %></li>
  <li><%= link_to "Log Out", destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to "Log In", new_user_session_path %></li>
  <li><%= link_to "Sign Up", new_user_join_path %></li>
<% end %>

app/views/layouts/_newsletter_form.html.erb
 <form action="index.html" method="post" class="form-inline" onsubmit="return false;">
    <div class="form-group">
        <label class="sr-only" for="register-email">Your Email</label>
        <div class="input-group">
            <input type="email" id="register-email" name="register-email" class="form-control" placeholder="Your Email..">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary">Subscribe</button>
            </span>
        </div>
    </div>
</form>

app/views/layouts/_social_links.html.erb
<li>
  <a href="https://www.facebook.com/hkStockOwl" class="social-facebook" data-toggle="tooltip" title="Like our Facebook page" target="_blank">
    <i class="fa fa-fw fa-facebook"></i>
  </a>
</li>
<li>
  <a href="https://twitter.com/hkStockOwl" class="social-twitter" data-toggle="tooltip" title="Follow us on Twitter" target="_blank">
    <i class="fa fa-fw fa-twitter"></i>
  </a>
</li>
<li>
  <a href="https://plus.google.com/+hkStockOwlPage/" class="social-google-plus" data-toggle="tooltip" title="Like our Google+ page" target="_blank">
    <i class="fa fa-fw fa-google-plus"></i>
  </a>
</li>

app/views/layouts/_support_links.html.erb
<li><%= link_to "<i class='fa fa-fw fa-support'></i> FAQ".html_safe, root_url %></li>
<li><%= link_to "<i class='fa fa-envelope'></i> Contact Us".html_safe, root_url %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "hkStockOwl" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "hkStockOwl" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<!-- Body -->
<body>
    <!-- Page Container -->
    <div id="page-container">
        <!-- Site Header -->
        <header>
            <%= render 'layouts/navigation' %>
        </header>
        <!-- END Site Header -->

        <%= yield %>

        <!-- Footer -->
        <footer class="site-footer site-section site-section-light">
            <%= render 'layouts/footer' %>
        </footer>
        <!-- END Footer -->
    </div>
    <!-- END Page Container -->

    <!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
    <a href="#" id="to-top"><i class="fa fa-arrow-up"></i></a>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "hkStockOwl" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "hkStockOwl" %>">
    <%= stylesheet_link_tag 'backend', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<!-- Body -->
<body>
  <!-- Login Container -->
  <div id="login-container">
    <!-- Login Header -->
    <h1 class="h2 text-light text-center push-top-bottom animation-slideDown">
        <strong>hkStockOwl</strong>
    </h1>
    <!-- END Login Header -->

    <%= render 'layouts/messages' %>

    <!-- Login Block -->
    <div class="block animation-fadeInQuickInv">
        <!-- Login Title -->
        <div class="block-title">
          <%= render 'devise/shared/links' %>
          <h2><%= content_for?(:title) ? yield(:title) : "hkStockOwl" %></h2>
        </div>
        <!-- END Login Title -->

        <%= yield %>
    </div>
    <!-- END Login Block -->

    <!-- Footer -->
    <footer class="text-muted text-center animation-pullUp">
      <small><span id="year-copy"></span> &copy; <%= link_to("hkStockOwl", root_path) %></small>
    </footer>
    <!-- END Footer -->
  </div>
  <!-- END Login Container -->
</body>
</html>